### ISSUE TITLE
Allow ignoring of notifications when setting start_down to true

### ISSUE THREAD

**Issue by martinisoft** [chef-cookbooks/runit#154]
Greetings,

I'd like to short-circuit the restart action in the event `start_down` is set to true (which creates the down file telling runit to not automatically start the service). This would effectively make notifications like restart or hup become a no-op in Chef if the service is currently down or marked down. Might attempt a PR for this in the future, but also not sure if people want something like this.

**Comment by iennae** [comment]
@martinisoft Are you still interested in doing this? We happily accept PR and it sounds like at least a couple of other people are interested.

**Comment by martinisoft** [comment]
> Are you still interested in doing this? We happily accept PR and it sounds like at least a couple of other people are interested.

@iennae I could look into doing this as a hack day project. We're preparing to ramp down our usage of runit internally so my bandwidth for this is limited.

**Comment by iennae** [comment]
I think a lot of folks are shutting down their use of runit, so maybe we should retire this enhancement request? For a hack day project some freebsd cookbook help might be really good. Thoughts?

**Comment by martinisoft** [comment]
> I think a lot of folks are shutting down their use of runit, so maybe we should retire this enhancement request? For a hack day project some freebsd cookbook help might be really good. Thoughts?

Yeah I think I can close this down. FreeBSD is a bigger priority for me these days. 👍
