### ISSUE TITLE
Create action with restart_on_update starts service early

### ISSUE THREAD

**Issue by bison** [chef-cookbooks/runit#176]
I have a few instances of a pattern where I create a `runit_service` with `action :create`, but don't start and enable it until the after some other action like a deploy, or at the end of the run with a delayed notification. I don't think this is possible after the `restart_on_update` changes in #170.

Delayed notifications for inline resources are run at the end of the provider action, not the end of the Chef run: [docs in provider.rb](https://github.com/chef/chef/blob/master/lib/chef/provider.rb#L329-L333) -- So the new ruby blocks always start and enable the service immediately after creating it if `restart_on_update` is true.

I don't really know of a good a way around that, and maybe it's intended, but at the very least should probably be noted in the docs.

**Comment by cwjohnston** [comment]
Thanks for bringing this up, I think we'll address it via documentation.

**Comment by cwjohnston** [comment]
@bison would the approach described in #154 support your use case?

**Comment by jarig** [comment]
Also tackled the same issue, but from logstash cookbook. 
That makes the very first bootstrap to fail all the time and only second succeeds.

**Comment by cheeseplus** [comment]
This definitely isn't possible with use_inline_resources.
