### ISSUE TITLE
Source repo should be configurable instead of hardcoded to packagecloud

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/runit#204]
### Cookbook version

3.0.0
### Chef-client version

12.14
### Platform Details

workflow vanilla environment node bootstrap in air gapped env
### Scenario:

install push jobs client via delivery-base cookbook in air gapped environment
### Steps to Reproduce:

add delivery base to runlist. it'll fail on attempting to configure package cloud because it cant reach outside.
### Expected Result:

a way to install runit in air-gapped env
### Actual Result:

have to fork the cookbook to get going.

**Comment by tas50** [comment]
Any chance you can get a PR for this @vinyar

**Comment by tas50** [comment]
The default recipe simply sets up package cloud and installs the package. If the user needs to use their own repo it's best that they write their own recipe to install runit. The complexity of handling multiple repos would be more than just writing the wrapper.

**Comment by vinyar** [comment]
The original bug was about an LWRP that had package cloud repo hardcoded. Looks like the current version doesn't do that. So 👍

**Comment by tas50** [comment]
Oh yes the inclusion of the default recipe is gone now.
