### ISSUE TITLE
Provider waits forever if runit isn't installed

### ISSUE THREAD

**Issue by cholman-zd** [chef-cookbooks/runit#208]
### Cookbook version
1.8.0

### Chef-client version
12.8.0

### Platform Details
Ubuntu 12.04

### Scenario:
Accidentally running a cookbook without having included the runit recipe, so runit is not installed

[This line](https://github.com/chef-cookbooks/runit/blob/772e1202cfc4e0d9268a4783d502141e80f00a4a/libraries/helpers.rb#L79) stalls forever.

### Steps to Reproduce:

Use the `runit` provider without having included the `runit` recipe and without `runit` installed on the system.

(we have abstracted the runit cookbook a bit. If the problem/fix isn't immediately obvious, let me know and I'll put together an actual example)

### Expected Result:
Some kind of a timeout or exception

### Actual Result:
It sits there forever waiting like Fry's dog does in that episode of futurama that made everyone cry.

**Comment by tas50** [comment]
This has been fixed in 3.0.2
