### ISSUE TITLE
User controller service creation blocked forever (Debian Stretch 9.0)

### ISSUE THREAD

**Issue by fancyweb** [chef-cookbooks/runit#219]
### Cookbook version
3.0.5

### Chef-client version
13.1.31

### Platform Details
Debian Stretch 9.0

### Scenario:
Create an user controlled service

### Steps to Reproduce:
This is how I was using the recipe before upgrading to the new Debian : 
```rb
include_recipe 'runit'

runit_service "es-core-visible" do
  owner "vagrant"
  group "vagrant"
  log false
end
```

### Expected Result:
The user controlled service gets created

### Actual Result:
The installations hangs on forever with this line : "ruby_block[wait for es-core-visible service socket] action run" because runit never starts.

### Fix and explanation
I'm copying the changelog from runit 2.1.2-4 which was installed : 

> Runit no longer provides /sbin/runsvdir-start symbolic link to
> /etc/runit/2. Everything this package provides now directly
> refers to /etc/runit/2, including systemd's service file, but
> scripts and configuration outside may be need updated.

To make it work I did this in my own recipe :
```rb
node.default['runit']['start'] = '/etc/runit/2'
```

**Comment by fancyweb** [comment]
Ok actually to make it work correctly on first provision I had to do : 
```rb
include_recipe 'runit'
execute 'runsvdir-start' do
  command '/etc/runit/2 &'
end
```

Because even if I change the "start" attribute or if I manually do the symbolic link, it gets stuck because it is never launched.

**Comment by tas50** [comment]
I fixed this on master. Thanks for the report
