### ISSUE TITLE
Runit doesn't start automatically at system startup anymore (Debian Stretch 9.0)

### ISSUE THREAD

**Issue by fancyweb** [chef-cookbooks/runit#220]
### Cookbook version
3.0.5

### Chef-client version
13.1.31

### Platform Details
Debian Stretch 9.0

### Expected Result:
My created user controlled services should automatically start on system startup.

### Actual Result:
They are not running.
If I launch them manually this is the message I can see : 
"Jun 21 12:21:37 stretch es-core-visible[1714]: fail: es-core-visible: runsv not running
Jun 21 12:21:37 stretch systemd[1]: Started LSB: initscript for runit-managed es-core-visible service."

So runit was not started on system startup.

### Fix and explanation
I'm copying the changelog from runit 2.1.2-4 which was installed : 

> Remove scripting in runit's maintainer scripts to adjust /etc/inittab.
> It is provided as separate binary package 'runit-sysv'.

To make it work I did this in my own recipe :
```rb
apt_package 'runit-sysv'
```

**Comment by jsirex** [comment]
On Debian Stretch systemd is default init system. Probably we should install 'runit-systemd'

**Comment by tas50** [comment]
Resolved by https://github.com/chef-cookbooks/runit/pull/224

**Comment by arkuzo** [comment]
thanx a lot :)
So simple and uneven solution :)
