### ISSUE TITLE
Runit not installed on Amazon Linux under Chef 13

### ISSUE THREAD

**Issue by caussourd** [chef-cookbooks/runit#221]
### Cookbook version
3.0.5

### Chef-client version
13.6.0

### Platform Details
Amazon Linux

### Scenario:
Install runit

### Steps to Reproduce:
Run `runit::default`

### Expected Result:
runit installed

### Actual Result:
runit not installed

It seems that since Chef 13, the `platform_family` for Amazon Linux is `amazon` and not `rhel` anymore. Consequently it doesn't install on Amazon Linux anymore.
https://github.com/chef-cookbooks/runit/blob/master/recipes/default.rb

**Comment by ff-pjha** [comment]
I am facing the same issue, had you got any solution for this ?

**Comment by tas50** [comment]
This has been fixed in the latest release. Give it a try and let me know if you're still having issues
