### ISSUE TITLE
Runit not getting installed 

### ISSUE THREAD

**Issue by ff-pjha** [chef-cookbooks/runit#222]
### Cookbook version
[3.0.5]

### Chef-client version
[ 12.5.1]

### Platform Details
[Amazon Linux]

### Scenario:
[Basically I am installing graphite cookbook, it is dependent on runit cookbook, and its failing]

### Steps to Reproduce:
[Run runit::default]

### Expected Result:
[runit installed]

### Actual Result:
[runit not installed]

===============================================================================
 Recipe: runit::default
         * service[runit] action nothing (skipped due to action :nothing)
         * execute[start-runsvdir] action nothing (skipped due to action :nothing)
         * packagecloud_repo[imeyer/runit] action add
           * yum_package[pygpgme] action install
             - install version 0.3-9.12.amzn1 of package python26-pygpgme
           * log[pygpgme_warning] action write (skipped due to not_if)
           * ruby_block[disable repo_gpgcheck if no pygpgme] action run (skipped due to not_if)
           * template[/etc/yum.repos.d/imeyer_runit.repo] action create
             - create new file /etc/yum.repos.d/imeyer_runit.repo
             - update content in file /etc/yum.repos.d/imeyer_runit.repo from none to c89480
             --- /etc/yum.repos.d/imeyer_runit.repo	2017-11-15 09:52:10.331997906 +0000
             +++ /etc/yum.repos.d/.imeyer_runit.repo20171115-2683-jighiv	2017-11-15 09:52:10.331997906 +0000
             @@ -1 +1,11 @@
             +[imeyer_runit]
             +name=imeyer_runit
             +baseurl=https://packagecloud.io/imeyer/runit/el/6/$basearch
             +repo_gpgcheck=1
             +gpgcheck=0
             +enabled=1
             +gpgkey=https://packagecloud.io/imeyer/runit/gpgkey
             +sslverify=1
             +sslcacert=/etc/pki/tls/certs/ca-bundle.crt
             +metadata_expire=300
             - change mode from '' to '0644'
           * execute[yum-makecache-imeyer_runit] action run
             
             ================================================================================
             Error executing action `run` on resource 'execute[yum-makecache-imeyer_runit]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of yum -q makecache -y --disablerepo=* --enablerepo=imeyer_runit ----
             STDOUT: 
             STDERR: Existing lock /var/run/yum.pid: another copy is running as pid 14602.
             Another app is currently holding the yum lock; waiting for it to exit...
        The other application is: yum
          Memory :  90 M RSS (300 MB VSZ)
          Started: Wed Nov 15 09:52:07 2017 - 00:04 ago
          State  : Running, pid: 14602
             Another app is currently holding the yum lock; waiting for it to exit...
        The other application is: yum
          Memory : 182 M RSS (392 MB VSZ)
          Started: Wed Nov 15 09:52:07 2017 - 00:06 ago
          State  : Running, pid: 14602
             Importing GPG key 0xD59097AB:
       Userid     : "packagecloud ops (production key) <ops@packagecloud.io>"
       Fingerprint: 418a 7f2f b0e1 e6e7 eabf 6fe8 c2e7 3424 d590 97ab
       From       : https://packagecloud.io/imeyer/runit/gpgkey
             https://packagecloud.io/imeyer/runit/el/6/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for imeyer_runit
             Trying other mirror.

**Comment by ff-pjha** [comment]
Basically the repo (imeyer_runit.repo) is not getting created inside yum.repos.d. Because of this the installation will not happen and the script of runit will not be created inside init.d. 
Please provide a solution for this.

**Comment by tas50** [comment]
This has been resolved in 3.0.6
