### ISSUE TITLE
runit version 4.0.0 breaks chefspec in consuming cookbook

### ISSUE THREAD

**Issue by lehn-etracker** [chef-cookbooks/runit#225]
### Cookbook version
4.0.0

### Chef-client version
chefspec (7.1.0)
chef (12.21.4)

### Platform Details
debian jessie (8.8)

### Scenario:
try to run chefspec in consumer cookbook using runit as dependency in metadata.rb

### Steps to Reproduce:
call chefspec

### Expected Result:
chefspec works

### Actual Result:

     TypeError:

       superclass mismatch for class RunitService
     # /tmp/chefspec20171128-32528-18omwrvfile_cache_path/cookbooks/runit/libraries/resource_runit_service.rb:27:in `<class:Resource>'
     # /tmp/chefspec20171128-32528-18omwrvfile_cache_path/cookbooks/runit/libraries/resource_runit_service.rb:25:in `<class:Chef>'
     # /tmp/chefspec20171128-32528-18omwrvfile_cache_path/cookbooks/runit/libraries/resource_runit_service.rb:24:in `<top (required)>'
     # ./spec/unit/recipes/default_spec.rb:13:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:44:in `block (4 levels) in <top (required)>'

**Comment by tas50** [comment]
This should be resolved in the 4.0.1 release. Sorry for the breakage here.
