### ISSUE TITLE
Error executing action `start` on resource 'service[runsvdir-start]'   STDERR: start: Unknown job: runsvdir-start

### ISSUE THREAD

**Issue by coltrey** [chef-cookbooks/runit#229]
I have a wrapper cookbook around the Jenkins cookbook which depends on runit.  After switching to 4.0.3 to fix [227](https://github.com/chef-cookbooks/runit/issues/227), the service can no longer be started.

It seems like runsvdir-start is not available on the host. 
The commands runsv, runsvchdir and runsvdir are available.

Does [this](https://github.com/chef-cookbooks/runit/blame/e508b510ba89e18da38ee00442de4d125b675bc0/recipes/default.rb#L58) depend on a more recent release of AWS Linux?

In the meantime, I've reverted to 3.0.6 and this is working.

### Cookbook version
4.0.3

### Chef-client version
12

### Platform Details
AWS Amazon Linux 2016-09 Opsworks Stacks

### Expected Result:
Service to be provisioned

### Actual Result:
```
[2017-11-29T21:47:26+00:00] INFO: Processing service[runsvdir-start] action start (runit::default line 66)

================================================================================
Error executing action `start` on resource 'service[runsvdir-start]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start runsvdir-start ----
STDOUT: 
STDERR: start: Unknown job: runsvdir-start
---- End output of /sbin/start runsvdir-start ----
Ran /sbin/start runsvdir-start returned 1

Resource Declaration:
---------------------
# In /var/chef/runs/364353c7-8440-44a7-bb9f-98a7a08dffef/local-mode-cache/cache/cookbooks/runit/recipes/default.rb

 66: service plat_specific_sv_name do
 67:   action [:start, :enable]
 68:   # this might seem crazy, but RHEL 6 is in fact Upstart and the runit service is upstart there
 69:   provider Chef::Provider::Service::Upstart if platform?('amazon') || platform_family?('rhel') && node['platform_version'].to_i == 6
 70:   not_if { platform?('debian') && node['platform_version'].to_i < 8 } # there's no init script on debian 7...for reasons
 71: end

Compiled Resource:
------------------
# Declared in /var/chef/runs/364353c7-8440-44a7-bb9f-98a7a08dffef/local-mode-cache/cache/cookbooks/runit/recipes/default.rb:66:in `from_file'

service("runsvdir-start") do
  provider Chef::Provider::Service::Upstart
  action [:start, :enable]
  supports {:restart=>nil, :reload=>nil, :status=>nil}
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  service_name "runsvdir-start"
  pattern "runsvdir-start"
  declared_type :service
  cookbook_name "runit"
  recipe_name "default"
  not_if { #code block }
end

Platform:
---------
x86_64-linux

```

**Comment by tas50** [comment]
@coltrey Can you fire up chef-shell and tell me what this returns:

```ruby
node['platform_version'].to_i >= 7 && !platform?('amazon')
```

Right now in Travis and locally amazon is properly trying to start the runsvdir service

**Comment by coltrey** [comment]
```
chef > node['platform_version'].to_i >= 7 && !platform?('amazon')
 => false
chef (12.7.2)>

chef (12.7.2)> node['platform_version'].to_i
 => 2016
chef (12.7.2)> !platform?('amazon')
 => false
chef (12.7.2)>

```

**Comment by tas50** [comment]
I'm having trouble reproducing this one. We have integration tests in Travis running on Amazon Linux w/o issue and I added chefspecs for the current logic which starts the service. It's all coming back green for Amazon Linux. Can you make sure you have the latest runit and jenkins cookbooks. Also if possible can you update to a more recent release of chef-client. Chef 12 goes EOL in April and Chef 13 has been out for about 8 months at this point.

**Comment by coltrey** [comment]
@tas50 
I had a chance to look at it more deeply this morning and the problem is that [this commit](https://github.com/chef-cookbooks/runit/commit/b192bab8108b946de90edbd4556dc6f00db613c7) isn't in 4.0.3.

Since I'm running on AWS Opsworks Stacks, I'm limited to the version of chef they're supporting, which for now is only 12.

**Comment by jshrack-ssi** [comment]
@tas50 @coltrey is correct. Version 4.0.3 is missing the referenced commit which would make this work on Amazon instances. Would it be possible to either commit the change to 4.0.3 or generate a new tagged build which includes the commit? This is a hard block for those of us who use Amazon AMIs and the runit cookbook.

**Comment by coltrey** [comment]
@jshrack-ssi The workaround I used was to go with 3.0.6.  You could probably also specify the specific commit in your Berksfile.

**Comment by tas50** [comment]
I pushed 4.04. Give it a try. It has a pile of expanded testing for exactly this scenario in addition to some fixes and general cleanup

**Comment by coltrey** [comment]
I verified 4.0.4 is working for me.
