### ISSUE TITLE
initial cookbook runs intermittently breaking yum

### ISSUE THREAD

**Issue by in4mer** [chef-cookbooks/runit#233]
### Cookbook version
4.1.1

### Chef-client version
12.19.36

### Platform Details
amazon linux 2016.03, 2017.09

### Scenario:
Your cookbook yum resources keep breaking my chef-client runs

### Steps to Reproduce:
It happens about 70% of the time, across different machines, etc.

### Expected Result:
I expect yum to not throw errors and my chef-client run to finish normally

### Actual Result:
https://pastebin.ca/4029031

**Comment by tas50** [comment]
The yum package resource in Chef has been entirely rewritten to work around multiple corruption bugs in the yum subsystem in RHEL distros. You'll need to update to the latest release of Chef though. Chef 12 is entirely end of life at this point.
