### ISSUE TITLE
options attribute of runit LWRP will not play along with `lazy`

### ISSUE THREAD

**Issue by avishai-ish-shalom** [chef-cookbooks/runit#51]
because options attribute getter/setter will try merge in env_dir, it tries to call merge! on DelayedEvaluator object.

**Comment by iennae** [comment]
@avishai-ish-shalom Apologies for the delay in any kind of response here. I'm wondering if this is still an issue for you and if so can you provide more details?

**Comment by lamont-granquist** [comment]
probably still an issue:

https://github.com/chef-cookbooks/runit/blob/master/libraries/resource_runit_service.rb#L132

**Comment by tas50** [comment]
Yep this is certainly an issue and we should change how we handle the options merging to make this work. It's a valid use case.

**Comment by tas50** [comment]
This whole resource has been refactored in a way that lazy should work now
