### ISSUE TITLE
runit_service not restarted on env change

### ISSUE THREAD

**Issue by singlethink** [chef-cookbooks/runit#71]
When the `env` values passed to an `runit_service` resource change, the service should be restarted to ensure that it picks up on the intended changes to its environment.  However, it appears that the environment values [are not checked](https://github.com/hw-cookbooks/runit/blob/bf0c2428b2c0c344c650108a82c9ab2a55d54626/libraries/provider_runit_service.rb#L98-L100) when determining whether or not the service should be restarted.

An additional check, such as the following, would probably suffice:

``` ruby
restart_service if @new_resource.restart_on_update && env_files.any? { |file| file.updated_by_last_action? }
```

**Comment by tas50** [comment]
Fixed in 3.0.1
