### ISSUE TITLE
add capability to restart svlog service

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/runit#72]
It is sometimes desirable to have the log service `svlogd` be restarted, especially if rendering the log configuration file.

For example, we have a workaround for this in [one of our Chef Server cookbooks](https://github.com/opscode-cookbooks/enterprise-chef-common/commit/9cf2443e648dac9e686e1044a1ed2f89f23858a1)

**Comment by cwjohnston** [comment]
I think this this solved as of #121?

**Comment by jtimberman** [comment]
That's different. This is specifically about the svlogd service that gets spawned by runit to capture the service's stdout.

**Comment by jtimberman** [comment]
By "That's Different™" I mean, that was to readd the normal "restart" action back to the runit_service resource.

**Comment by cwjohnston** [comment]
Ah yes, I see. I failed to read all the words. :+1:
